<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Image2Gdram.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Presets\presets.json" LogicalName="Image2Gdram.Core.Presets.presets.json" />
  </ItemGroup>

</Project>
