<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Image2Gdram.OutputSamples</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Image2Gdram.Core\Image2Gdram.Core.csproj" />
    <ProjectReference Include="..\TestAssetsGenerator\TestAssetsGenerator.csproj" />
  </ItemGroup>

</Project>
