<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Image2Gdram.TestAssets</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tests\Image2Gdram.Reference\Image2Gdram.Reference.csproj" />
  </ItemGroup>

</Project>
