<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Image2Gdram.UiProbe</RootNamespace>
    <ApplicationManifest>..\..\src\image2gdram_converter\app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\image2gdram_converter\image2gdram_converter.csproj" />
  </ItemGroup>

</Project>
