<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Image2Gdram.Imaging.Wic</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Image2Gdram.Core\Image2Gdram.Core.csproj" />
  </ItemGroup>

</Project>
